'use client';

import React from 'react';
import Link from 'next/link';

export default function ExplorePage() {
  const destinations = [
    {
      name: 'Tokyo, Japan',
      emoji: '🌸',
      description: 'Experience futuristic skyscrapers, historical temples, and world-class sushi guides.',
      tags: ['Culture', 'Food', 'Modern'],
      days: 5,
    },
    {
      name: 'Paris, France',
      emoji: '🗼',
      description: 'Stroll along the Seine, explore the Louvre museum, and dine at exquisite cafes.',
      tags: ['Romantic', 'Art', 'History'],
      days: 4,
    },
    {
      name: 'Reykjavik, Iceland',
      emoji: '🏔️',
      description: 'Bathe in geothermal springs, hike active volcanoes, and marvel at the Northern Lights.',
      tags: ['Nature', 'Adventure', 'Scenic'],
      days: 7,
    },
    {
      name: 'Rome, Italy',
      emoji: '🏛️',
      description: 'Uncover ancient history at the Colosseum, make a wish at Trevi Fountain, and eat pizza.',
      tags: ['History', 'Culture', 'Culinary'],
      days: 3,
    },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 flex-grow space-y-12 relative">
      <div className="absolute top-1/3 left-1/3 w-80 h-80 bg-teal-500/5 rounded-full blur-[90px] pointer-events-none" />

      {/* Page Header */}
      <div className="text-center max-w-2xl mx-auto space-y-4">
        <h1 className="text-4xl font-extrabold tracking-tight">
          Explore Popular Destinations
        </h1>
        <p className="text-zinc-500 dark:text-zinc-400">
          Browse through templates generated by our community and AI travel consultants.
        </p>
      </div>

      {/* Destinations Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {destinations.map((dest, i) => (
          <div
            key={i}
            className="group bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 rounded-3xl p-6 sm:p-8 shadow-sm hover:shadow-xl hover:translate-y-[-4px] transition-all duration-300 flex flex-col justify-between"
          >
            <div>
              <div className="flex justify-between items-start">
                <h3 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 group-hover:text-teal-600 dark:group-hover:text-teal-400 transition-colors">
                  {dest.name}
                </h3>
                <span className="text-4xl">{dest.emoji}</span>
              </div>
              <p className="text-zinc-500 dark:text-zinc-450 mt-3 text-sm leading-relaxed">
                {dest.description}
              </p>
              
              <div className="flex flex-wrap gap-2 mt-6">
                {dest.tags.map((tag) => (
                  <span
                    key={tag}
                    className="text-xs font-semibold px-2.5 py-1 bg-zinc-100 dark:bg-zinc-800 text-zinc-500 dark:text-zinc-455 rounded-lg"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </div>

            <div className="mt-8 pt-4 border-t border-zinc-100 dark:border-zinc-800 flex justify-between items-center text-sm">
              <span className="text-zinc-400 font-medium">⏳ {dest.days} Days Itinerary</span>
              <Link
                href={`/dashboard?destination=${encodeURIComponent(dest.name)}`}
                className="font-bold text-teal-600 dark:text-teal-400 hover:text-teal-500 transition-colors inline-flex items-center gap-1"
              >
                Use Template
                <svg className="w-4 h-4 transform group-hover:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
                </svg>
              </Link>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
